language: java
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk15
  - openjdk11
  - openjdk8

env:
  global:
    - secure: "A3i6zmtUzZO/i4+B1BR0DtPNdrCjJceSRuMwqEuqnxVPI/ABWtXqfrjNLRuQDuysVJTyieFUa1D4A0rgn2FZNV7nmPzTebPOC8xZcneQWzOyzWhvndFPme41NtXjSER3qQqI+Zy6ESaErraKZEwoZXM1lOhQANks3hGXAmxAOZw=" # GH_TOKEN

  matrix:
    - LABEL=mvn        CMD="mvn -B -P!standard-with-extra-repos verify --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true" INSTALL="mvn -P!standard-with-extra-repos dependency:go-offline test clean --quiet --fail-never -DskipTests=true"

install:
  - ${INSTALL}

script:
  - ${CMD}

after_success:
  - util/publish-latest-docs.sh
  - util/publish-snapshot-on-commit.sh

branches:
  only:
    - master
